name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # 使用JDK 11（兼容大多数Gradle版本）
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission
        run: chmod +x gradlew

      # 清理Gradle旧缓存
      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/
          ./gradlew --stop

      - name: Build with retry
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon || \
          (sleep 5 && ./gradlew assembleDebug --stacktrace --no-daemon)
