name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build signed APK
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        run: |
          echo "$KEYSTORE" > keystore.jks | base64 -d
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASS

      - name: Capture build info
        run: |
          ./gradlew signingReport > signing_report.txt
          echo "BUILD_TYPE=release" >> $GITHUB_ENV

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: |
            app/build/outputs/apk/release/app-release.apk
            signing_report.txt

      - name: Upload mapping
        if: ${{ env.BUILD_TYPE == 'release' }}
        uses: actions/upload-artifact@v4
        with:
          name: mapping
          path: app/build/outputs/mapping/release/
