
name: Android Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      # 使用JDK 11（兼容大多数Gradle版本）
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Grant execute permission
        run: chmod +x gradlew

      # 清理Gradle旧缓存
      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/
          ./gradlew --stop

      - name: Build with retry
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon || \
          (sleep 5 && ./gradlew assembleDebug --stacktrace --no-daemon)
      
      # 添加APK文件验证步骤（调试用）
      - name: Verify APK exists
        run: |
          ls -la app/build/outputs/apk/debug/
          if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "APK文件未生成！"
            exit 1
          fi

      # 上传APK文件
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7  # 设置保留天数（可选）
